# Generated by Django 6.1.1 on 2026-10-02 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_backfill_email_addresses'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.CharField(blank=True, max_length=64, verbose_name='Time zone'),
        ),
    ]
