# Generated by Django 6.1.1 on 2026-10-03 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_format',
            field=models.CharField(blank=True, max_length=16, verbose_name='Date format'),
        ),
        migrations.AddField(
            model_name='user',
            name='time_format',
            field=models.CharField(blank=True, max_length=2, verbose_name='Time format'),
        ),
    ]
