# Generated by Django 6.0.8 on 2026-08-29 16:58

import apps.links.utils
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('cards_per_row', models.PositiveSmallIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)], verbose_name='cards per row')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='order')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'link group',
                'verbose_name_plural': 'link groups',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.URLField(max_length=500, verbose_name='URL')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to=apps.links.utils.link_favicon_upload_to, verbose_name='favicon')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='order')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_links', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='links.linkgroup', verbose_name='group')),
            ],
            options={
                'verbose_name': 'link',
                'verbose_name_plural': 'links',
                'ordering': ['order', 'id'],
            },
        ),
    ]
