# Generated by Django 6.0.8 on 2026-08-22 13:46

import apps.attachments.utils
import apps.attachments.validators
import django.db.models.deletion
import taggit.managers
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('visibility', models.CharField(choices=[('public', 'Visible to everyone'), ('unlisted', 'Hidden, reachable via its own direct link'), ('shared', 'Hidden, reachable only via a generated share link'), ('private', 'Owner only')], db_index=True, default='private', max_length=16)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('remind_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_cover', models.BooleanField(default=False, help_text='Cover image/file for its target (e.g. an album note).')),
                ('file', models.FileField(max_length=500, upload_to=apps.attachments.utils.attachment_upload_to, validators=[apps.attachments.validators.validate_upload_size, apps.attachments.validators.validate_upload_extension])),
                ('kind', models.CharField(choices=[('image', 'Image'), ('document', 'Document'), ('audio', 'Audio'), ('video', 'Video'), ('other', 'Other')], db_index=True, default='other', max_length=16)),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=120)),
                ('size', models.PositiveBigIntegerField(default=0)),
                ('checksum', models.CharField(blank=True, db_index=True, max_length=64)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'ordering': ['position', 'id'],
                'indexes': [models.Index(fields=['content_type', 'object_id', 'position'], name='attachments_content_0a52cf_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_cover', True)), fields=('content_type', 'object_id'), name='attachments_one_cover_per_target')],
            },
        ),
    ]
