# Generated by Django 6.1.1 on 2026-10-02 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='visibility',
            field=models.CharField(choices=[('public', 'Visible to everyone'), ('unlisted', 'Hidden, reachable via its own direct link'), ('shared', 'Hidden, reachable only via a generated share link'), ('private', 'Owner only')], db_index=True, default='public', max_length=16),
        ),
    ]
