# Generated by Django 6.0.8 on 2026-08-22 13:46

import django.db.models.deletion
import taggit.managers
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('visibility', models.CharField(choices=[('public', 'Visible to everyone'), ('unlisted', 'Hidden, reachable via its own direct link'), ('shared', 'Hidden, reachable only via a generated share link'), ('private', 'Owner only')], db_index=True, default='private', max_length=16)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('remind_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=255)),
                ('kind', models.CharField(choices=[('note', 'Note'), ('album', 'Album'), ('purchase', 'Purchase'), ('warranty', 'Warranty'), ('contract', 'Contract'), ('reminder', 'Reminder')], db_index=True, default='note', max_length=16)),
                ('body_format', models.CharField(choices=[('html', 'HTML'), ('markdown', 'Markdown'), ('plain', 'Plain text')], default='html', max_length=16)),
                ('body', models.TextField(blank=True)),
                ('json_data', models.JSONField(blank=True, default=dict)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'ordering': ['path'],
            },
        ),
    ]
