# Generated by Django 6.1.1 on 2026-09-26 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_note_is_draft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='kind',
            field=models.CharField(choices=[('note', 'Note'), ('album', 'Album'), ('purchase', 'Purchase'), ('warranty', 'Warranty'), ('contract', 'Contract'), ('reminder', 'Reminder'), ('node', 'Node')], db_index=True, default='note', max_length=16),
        ),
        migrations.AlterField(
            model_name='note',
            name='visibility',
            field=models.CharField(choices=[('public', 'Visible to everyone'), ('unlisted', 'Hidden, reachable via its own direct link'), ('shared', 'Hidden, reachable only via a generated share link'), ('private', 'Owner only')], db_index=True, default='public', max_length=16),
        ),
    ]
