# Generated by Django 6.1.1 on 2026-10-02 19:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_note_kind_alter_note_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='all_day',
            field=models.BooleanField(default=False, verbose_name='All day'),
        ),
        migrations.AddField(
            model_name='note',
            name='color',
            field=models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'Enter a color as #rrggbb.')], verbose_name='Calendar color'),
        ),
        migrations.AddField(
            model_name='note',
            name='recurrence',
            field=models.CharField(blank=True, max_length=255, verbose_name='Repeat'),
        ),
        migrations.AddField(
            model_name='note',
            name='remind_minutes_before',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Remind before (minutes)'),
        ),
        migrations.AddField(
            model_name='note',
            name='starts_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Starts at'),
        ),
        migrations.AlterField(
            model_name='note',
            name='kind',
            field=models.CharField(choices=[('note', 'Note'), ('album', 'Album'), ('purchase', 'Purchase'), ('warranty', 'Warranty'), ('contract', 'Contract'), ('reminder', 'Reminder'), ('node', 'Node'), ('event', 'Event')], db_index=True, default='note', max_length=16),
        ),
    ]
