# Generated by Django 6.1.1 on 2026-10-03 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0004_note_calendar_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleCalendarAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('google_email', models.CharField(blank=True, max_length=254, verbose_name='Google account')),
                ('refresh_token_enc', models.TextField(blank=True)),
                ('access_token_enc', models.TextField(blank=True)),
                ('access_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('granted_scopes', models.TextField(blank=True, verbose_name='Granted scopes')),
                ('calendar_id', models.CharField(blank=True, max_length=255, verbose_name='Calendar')),
                ('calendar_summary', models.CharField(blank=True, max_length=255, verbose_name='Calendar name')),
                ('status', models.CharField(choices=[('active', 'Active'), ('needs_reconnect', 'Needs reconnecting'), ('error', 'Error')], db_index=True, default='active', max_length=20, verbose_name='Status')),
                ('sync_enabled', models.BooleanField(default=True, verbose_name='Sync enabled')),
                ('push_documents', models.BooleanField(default=True, verbose_name='Include document expiry dates')),
                ('sync_token', models.TextField(blank=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Last synced')),
                ('last_full_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='Last full sync')),
                ('retry_after', models.DateTimeField(blank=True, null=True)),
                ('consecutive_failures', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, verbose_name='Last error')),
                ('last_error_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_calendar', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Google Calendar account',
                'verbose_name_plural': 'Google Calendar accounts',
            },
        ),
        migrations.CreateModel(
            name='GoogleEventLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note_public_id', models.UUIDField(db_index=True, verbose_name='Note ID')),
                ('calendar_id', models.CharField(max_length=255, verbose_name='Calendar')),
                ('event_id', models.CharField(max_length=1024, verbose_name='Google event ID')),
                ('origin', models.CharField(choices=[('local', 'Created here'), ('google', 'Imported from Google')], max_length=10, verbose_name='Origin')),
                ('state', models.CharField(choices=[('active', 'Active'), ('detached', 'Detached')], db_index=True, default='active', max_length=10, verbose_name='State')),
                ('is_document', models.BooleanField(default=False, verbose_name='Document')),
                ('remote_editable', models.BooleanField(default=True)),
                ('etag', models.CharField(blank=True, max_length=255)),
                ('google_updated', models.DateTimeField(blank=True, null=True)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('note_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, verbose_name='Last error')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='events.googlecalendaraccount', verbose_name='Account')),
                ('note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='google_links', to='content.note', verbose_name='Note')),
            ],
            options={
                'verbose_name': 'Google event link',
                'verbose_name_plural': 'Google event links',
                'constraints': [models.UniqueConstraint(fields=('account', 'calendar_id', 'event_id'), name='events_gcal_link_event_uniq'), models.UniqueConstraint(condition=models.Q(('note__isnull', False), ('state', 'active')), fields=('account', 'note'), name='events_gcal_link_active_note_uniq')],
            },
        ),
    ]
