# Generated by Django 6.1.1 on 2026-10-03 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='googlecalendaraccount',
            name='oauth_client_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='OAuth client ID'),
        ),
        migrations.AddField(
            model_name='googlecalendaraccount',
            name='sync_direction',
            field=models.CharField(choices=[('both', 'Both ways'), ('from_google', 'Only from Google to this site'), ('to_google', 'Only from this site to Google')], default='both', max_length=20, verbose_name='Sync direction'),
        ),
        migrations.CreateModel(
            name='GoogleOAuthClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_id', models.CharField(max_length=255, verbose_name='Client ID')),
                ('client_secret_enc', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_oauth_client', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Google OAuth client',
                'verbose_name_plural': 'Google OAuth clients',
            },
        ),
    ]
