# Generated by Django 6.1.1 on 2026-10-03 17:11

import random
from datetime import timedelta

from django.db import migrations, models
from django.utils import timezone

# Spread over the default sync interval / a day, so that right after the
# deploy existing accounts don't all become due at the same moment.
SYNC_SPREAD = timedelta(minutes=10)
RECONCILE_SPREAD = timedelta(days=1)


def spread_schedule(apps, schema_editor):
    GoogleCalendarAccount = apps.get_model("events", "GoogleCalendarAccount")
    now = timezone.now()
    for account in GoogleCalendarAccount.objects.only("pk").iterator():
        GoogleCalendarAccount.objects.filter(pk=account.pk).update(
            next_sync_at=now + SYNC_SPREAD * random.random(),
            next_reconcile_at=now + RECONCILE_SPREAD * random.random(),
        )


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_googlecalendaraccount_oauth_client_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlecalendaraccount',
            name='next_reconcile_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Next reconcile'),
        ),
        migrations.AddField(
            model_name='googlecalendaraccount',
            name='next_sync_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Next sync'),
        ),
        migrations.AddField(
            model_name='googlecalendaraccount',
            name='push_pending',
            field=models.BooleanField(default=True, verbose_name='Push pending'),
        ),
        migrations.AddField(
            model_name='googlecalendaraccount',
            name='watch_calendar_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='Push channel calendar'),
        ),
        migrations.AddField(
            model_name='googlecalendaraccount',
            name='watch_channel_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Push channel'),
        ),
        migrations.AddField(
            model_name='googlecalendaraccount',
            name='watch_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Push channel expires'),
        ),
        migrations.AddField(
            model_name='googlecalendaraccount',
            name='watch_resource_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='googlecalendaraccount',
            name='watch_token',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.RunPython(spread_schedule, migrations.RunPython.noop),
    ]
